name : Manual approval

on:
  push:
    branches: ["main"]

jobs:
  annual-expenses:

    runs-on: ubuntu-latest
    environment:
      name: main


    steps:
    - uses: actions/checkout@v3
  
    - name: Print Hello
      run: echo "Hello"
